# Generated by Django 3.1.4 on 2020-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NearEarthObject",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("nasa_jpl_url", models.URLField(default="NO URL")),
                ("close_approach_date", models.DateTimeField(blank=True)),
                ("relative_velocity", models.FloatField(default=0)),
                ("estimated_diameter_min", models.FloatField(default=0)),
                ("estimated_diameter_max", models.FloatField(default=0)),
                ("is_potentially_hazardous", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["close_approach_date"],
            },
        ),
    ]
